# Generated by Django 4.2.1 on 2023-05-21 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('ABS', 'A'), ('PLA', 'P'), ('PETG', 'PE'), ('TPU', 'T')], max_length=255)),
                ('material_amount', models.IntegerField()),
                ('v_material', models.FloatField()),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Finished at')),
                ('status', models.CharField(choices=[('pending', 'p'), ('complete', 'c'), ('rejected', 'r')], default='pending', max_length=255)),
                ('price', models.FloatField(null=True)),
                ('file', models.FileField(upload_to='documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
